### ISSUE TITLE
publish typings to index.d.ts

### ISSUE THREAD

**Issue by searls** [testdouble/ought#2]

**Comment by ericqweinstein** [comment]
@searls Okay if I take this one? I don't have a _ton_ of TS experience, so may need a second set of eyes.

**Comment by searls** [comment]
Full disclosure: @garybernhardt will be those eyes.

![giphy](https://user-images.githubusercontent.com/79303/52985304-4b819900-33c1-11e9-9961-33cb09412776.gif)

**Comment by ericqweinstein** [comment]
Years of DAS have prepared me for this very moment

**Comment by garybernhardt** [comment]
👀
